name: Build sucrase

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION: 3.34.0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get-sucrase-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'alangpierce/sucrase'
          ref: main
          fetch-depth: 50

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout to hash
        run: |
          HASH=$(git log -1 --grep "v$VERSION" --pretty=format:'%H')
          git checkout $HASH
          git log -1 $HASH

      - name: Finding out dependency versions
        run: |
          yarn list --pattern 'ts-interface-checker|lines-and-columns' --depth 1 > yarn.txt
          grep '@' yarn.txt | awk '{ print $2 }' > versions.txt
          cat versions.txt

      - uses: actions/upload-artifact@v3
        with:
          name: versions
          path: versions.txt
          retention-days: 30

  build:
    runs-on: ubuntu-latest
    needs:
      - get-sucrase-deps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: actions/download-artifact@v3
        with:
          name: versions

      - name: Get sucrase build from NPM
        run: |
          npm ci
          npm i $(cat versions.txt)
          mkdir dist
          npm pack "sucrase@$VERSION"
          tar xzf sucrase-*.tgz
          rm sucrase-*.tgz

      - name: Rollup into IIFE
        run: |
          npx rollup -i ./package/dist/index.js \
            -f iife \
            -n sucrase \
            --banner "/* sucrase v$VERSION */" \
            -p '@rollup/plugin-node-resolve' \
            -p '@rollup/plugin-commonjs' \
            -p '@rollup/plugin-terser' \
            -o dist/sucrase.browser.js

      - name: Add version info
        working-directory: dist
        run: |
          echo "v$VERSION" > VERSION
          mv sucrase.browser.js sucrase.tmp.js
          echo "/* sucrase v$VERSION */" > sucrase.browser.js
          cat sucrase.tmp.js >> sucrase.browser.js
          rm sucrase.tmp.js

      - uses: actions/upload-artifact@v3
        with:
          path: dist/
          retention-days: 30

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: v3
          publish_dir: dist
          commit_message: build v${{ env.VERSION }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
