name: Build sucrase

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION: 3.34.0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'alangpierce/sucrase'
          ref: main
          fetch-depth: 20

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout to hash
        run: |
          HASH=$(git log -1 --grep "v$VERSION" --pretty=format:'%H')
          git checkout $HASH
          git log -1 $HASH

      - name: Finding out dependency versions
        run: |
          yarn list --pattern 'ts-interface-checker|lines-and-columns' --depth 1 > yarn.txt
          grep '@' yarn.txt | awk '{ print $2 }' > versions.txt
          cat versions.txt

      - uses: actions/upload-artifact@v3
        with:
          path: versions.txt
          retention-days: 30

  build:
    runs-on: ubuntu-latest
    needs:
      - get-versions
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: |
          npm ci
          mkdir dist
          npm pack "sucrase@$VERSION"
          tar xzf sucrase-*.tgz
          rm sucrase-*.tgz

      - run: |
          npx rollup -i ./package/dist/index.js \
            -f iife \
            -n sucrase \
            -p '@rollup/plugin-node-resolve' \
            -p '@rollup/plugin-commonjs' \
            -p '@rollup/plugin-terser' \
            -o dist/sucrase.browser.js

      - uses: actions/upload-artifact@v3
        with:
          path: dist/sucrase.browser.js
          retention-days: 10
